runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest



handlers:
- url: /newRequest
  script: submitRequest.app
  secure: always

- url: /editRequest
  script: submitRequest.app
  secure: always

- url: /newProposal(ForRequest)?
  script: submitProposal.app
  secure: always

- url: /editProposal
  script: submitProposal.app
  secure: always

- url: /newReason
  script: submitReason.app
  secure: always

- url: /editReason
  script: submitReason.app
  secure: always

- url: /submitVote
  script: submitVote.app
  secure: always

- url: /getRecent
  script: getRecent.app
  secure: always

- url: /getRequestData/.*
  script: getRequestData.app
  secure: always

- url: /getProposalData/.*
  script: getProposalData.app
  secure: always

- url: /getLogin
  script: submitLogin.app
  secure: always

- url: /createLogin
  script: submitLogin.app
  secure: always

- url: /loginReturn
  script: submitLogin.app
  secure: always

- url: /submitLogout
  script: submitLogin.app
  secure: always

- url: /signLoginRequest
  script: submitLogin.app
  secure: always

- url: /(.*\.(png|css|js))$
  static_files: \1
  upload: .*\.(png|css|js)$




- url: /autocomplete/newSurvey
  script: autocomplete.submitSurvey.app
  secure: always

- url: /autocomplete/getSurvey/.*
  script: autocomplete.getSurvey.app
  secure: always

- url: /autocomplete/editSurvey
  script: autocomplete.submitSurvey.app
  secure: always

- url: /autocomplete/reorderSurveyQuestions
  script: autocomplete.submitSurvey.app
  secure: always

- url: /autocomplete/editQuestion
  script: autocomplete.submitQuestion.app
  secure: always

- url: /autocomplete/getQuestion/.*
  script: autocomplete.getQuestion.app
  secure: always

- url: /autocomplete/getSurveyQuestions/.*
  script: autocomplete.getQuestion.app
  secure: always

- url: /autocomplete/getQuestionAnswersFromCreator/.*
  script: autocomplete.getAnswers.app
  secure: always

- url: /autocomplete/deleteQuestion
  script: autocomplete.submitQuestion.app
  secure: always

- url: /autocomplete/editAnswer
  script: autocomplete.submitAnswer.app
  secure: always

- url: /autocomplete/deleteAnswer
  script: autocomplete.submitAnswer.app
  secure: always

- url: /autocomplete/setAnswer
  script: autocomplete.submitAnswer.app
  secure: always

- url: /autocomplete/getQuestionAnswersForPrefix/.*
  script: autocomplete.getAnswers.app
  secure: always

- url: /autocomplete/getQuestionFrequentAnswers/.*
  script: autocomplete.getAnswers.app
  secure: always

- url: /autocomplete/getUserAnswer/.*
  script: autocomplete.getAnswers.app
  secure: always

- url: /autocomplete/getUserAnswers/.*
  script: autocomplete.getAnswers.app
  secure: always

- url: /autocomplete/getRecent
  script: autocomplete.getRecent.app
  secure: always

- url: /autocomplete/?
  script: autocomplete.main.app
  secure: always




- url: /procon
  script: main.app
  secure: always

- url: /.*
  script: siteList.app
  secure: always

